com.fasterxml.jackson.*:* = 2.20.0
com.fasterxml.jackson.core:jackson-annotations = 2.20
org.junit.jupiter:* = 6.0.1
org.junit.platform:* = 6.0.1
org.junit.vintage:* = 6.0.1
com.google.guava:guava = 33.5.0-jre
junit:junit = 4.13.2
org.assertj:assertj-core = 3.27.6
org.immutables:* = 2.11.6
org.mockito:mockito-core = 5.20.0
org.slf4j:* = 2.0.17
com.palantir.tritium:* = 0.112.0
com.palantir.conjure.java:* = 8.61.0
com.palantir.conjure.java.runtime:* = 8.25.0
com.palantir.conjure:conjure = 4.52.0
com.palantir.sls.versions:* = 1.8.0
com.squareup:javapoet = 1.13.0
com.atlassian.commonmark:* = 0.12.1
org.apache.commons:commons-lang3 = 3.19.0
com.netflix.nebula:nebula-test = 10.6.2
com.palantir.safe-logging:preconditions = 3.9.0
com.palantir.goethe:* = 0.17.0
commons-io:commons-io = 2.20.0

# conflict resolution
com.google.code.findbugs:jsr305 = 3.0.2
com.google.errorprone:error_prone_annotations = 2.11.0
