com.fasterxml.jackson.*:* = 2.19.2
org.junit.jupiter:* = 5.13.4
org.junit.platform:* = 1.13.4
org.junit.vintage:* = 5.13.4
com.google.guava:guava = 33.4.8-jre
junit:junit = 4.13.2
org.assertj:assertj-core = 3.27.3
org.immutables:* = 2.11.2
org.mockito:mockito-core = 5.18.0
org.slf4j:* = 2.0.17
com.palantir.tritium:* = 0.102.0
com.palantir.conjure.java:* = 8.50.0
com.palantir.conjure.java.runtime:* = 8.22.0
com.palantir.conjure:conjure = 4.52.0
com.palantir.sls.versions:* = 1.5.0
com.squareup:javapoet = 1.13.0
com.atlassian.commonmark:* = 0.12.1
org.apache.commons:commons-lang3 = 3.18.0
com.netflix.nebula:nebula-test = 10.6.2
com.palantir.safe-logging:preconditions = 3.9.0
com.palantir.goethe:* = 0.16.0
commons-io:commons-io = 2.20.0

# conflict resolution
com.google.code.findbugs:jsr305 = 3.0.2
com.google.errorprone:error_prone_annotations = 2.11.0
